#!/usr/bin/perl
use Time::Local;
use Term::ANSIColor;
use Data::Dumper;
use Cwd 'abs_path';
use File::Basename;

my $EXECPATH = abs_path(dirname(__FILE__));
$SLURMDIR= "/usr/local/bin";

$sinfo = `$SLURMDIR/sinfo -o "%n %e %m %a %c %C" -h`;
$squeue = `$SLURMDIR/squeue --format="%i %.9P %.30j %.8u %.8T %.10M %.9l %.10D %R " -h`;
open HAND, '<', "$EXECPATH/nodes.txt";
%nodeClass = map {chomp; split /\t+/} (<HAND>);


my @nodes = split "\n", $sinfo;
my @jobs = split "\n", $squeue;

foreach my $n (@nodes)
{

	my @lines = split /\s+/, $n;
	my $node = $lines[0];
	my @nodeCores = split "/", $lines[5];
	$nodeprops{$node}{status}=$lines[3];
	$nodeprops{$node}{cores}=$lines[4];
	$nodeprops{$node}{coresinuse}=$nodeCores[0];
	$nodeprops{$node}{coresfree}=$nodeCores[1];
}

foreach my $n (@jobs)
{
	my @lines = split /\s+/, $n;
	my $user = $lines[3];
	my $jobID = $lines[0];
	my $nodeList = $lines[8];
	my @jobNodes;
	while ($nodeList =~ /(compute\d\d\d)/g)
	{
		push @jobNodes, $1;
	}
	while ($nodeList =~ /\[(\d\d\d)-(\d\d\d)\]/g)
	{
		for my $i ($1..$2)
		{
			push @jobNodes, sprintf("compute%03d", $i);
		}
	}
	for my $j (@jobNodes)
	{
		$nodeprops{$j}{job}{$jobID}{user} = $user;
	}
}
#print Dumper(%nodeprops);

foreach $k (sort keys %nodeprops)
{
	
	$color = $nodeprops{$k}{job}  ? "red" : "green";
	print color($color) . "$k   " . $nodeClass{$k} . "\t" . color("reset");
	print "$nodeprops{$k}{cores}core\t";
	
    for my $j (keys %{ $nodeprops{$k}{job} }) {
      print "[" . color("cyan") . "#$j" . color("reset") . ":" . color("yellow") .  $nodeprops{$k}{job}{$j}{user} . color("reset") . "]";
    }
	print  "\t" . $nodeprops{$k}{coresinuse} . " cores active" if %{ $nodeprops{$k}{job}};

	print color("green") . "FREE" .  color("reset") if ! %{ $nodeprops{$k}{job}};
	print color("red") . "NODE IS OFFLINE" .  color("reset") if $nodeprops{$k}{status} !~ /up/;
	print "\n";

}

#system "echo " . time . " " . $ENV{USER} ." >> $root_directory/log/access.log";
